# OpenAPI Specification for Frontend API Interactions (Placeholder)

This YAML file describes the API endpoints that the frontend application will consume from the backend.
It serves as a contract between the frontend and backend development.

## Version
openapi: 3.0.0
info:
  title: Todo Frontend API Contract
  version: 1.0.0
  description: API endpoints consumed by the Todo frontend application.

servers:
  - url: http://localhost:8000/api/v1
    description: Local Development Server

paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '201':
          description: User successfully registered and logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  access_token:
                    type: string
                  token_type:
                    type: string
        '400':
          description: Invalid input

  /auth/login:
    post:
      summary: Authenticate user and get JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: User successfully logged in
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                  token_type:
                    type: string
        '401':
          description: Invalid credentials

  /tasks:
    get:
      summary: Retrieve all tasks for the authenticated user
      security:
        - BearerAuth: []
      responses:
        '200':
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized

    post:
      summary: Create a new task
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
        '400':
          description: Invalid input

  /tasks/{task_id}:
    get:
      summary: Retrieve a specific task by ID
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
        '404':
          description: Task not found

    put:
      summary: Update a specific task by ID
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized
        '404':
          description: Task not found
        '400':
          description: Invalid input

    delete:
      summary: Delete a specific task by ID
      security:
        - BearerAuth: []
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Task successfully deleted
        '401':
          description: Unauthorized
        '404':
          description: Task not found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - status
        - user_id
      properties:
        id:
          type: string
          description: Unique identifier for the task
        title:
          type: string
          description: Brief name of the task
        description:
          type: string
          nullable: true
          description: Detailed explanation of the task
        status:
          type: string
          enum: [pending, completed]
          description: Current status of the task
        due_date:
          type: string
          format: date-time
          nullable: true
          description: When the task is due
        priority:
          type: string
          enum: [low, medium, high]
          nullable: true
          description: Priority level of the task
        tags:
          type: array
          items:
            type: string
          nullable: true
          description: List of tags for categorization
        user_id:
          type: string
          description: ID of the user who owns the task
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true

    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
        description:
          type: string
          nullable: true
        due_date:
          type: string
          format: date-time
          nullable: true
        priority:
          type: string
          enum: [low, medium, high]
          nullable: true
        tags:
          type: array
          items:
            type: string
          nullable: true

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
          nullable: true
        status:
          type: string
          enum: [pending, completed]
        due_date:
          type: string
          format: date-time
          nullable: true
        priority:
          type: string
          enum: [low, medium, high]
          nullable: true
        tags:
          type: array
          items:
            type: string
          nullable: true
